apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql
  - provider.yaml
  - provider-config.yaml

components:
- ../../components/provider

replacements:
- source: 
    kind: Provider
    fieldPath: metadata.name
  targets:
  - select:
      kind: Composition
    fieldPaths: 
    - metadata.labels.provider
    options:
      create: true
- source:
    kind: ProviderConfig
    fieldPath: metadata.labels.location
  targets:
  - select:
      kind: Composition
    fieldPaths:
    - spec.resources.*.base.spec.forProvider.location
    # options:
    #   create: true
