apiVersion: azure.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: provider-azure-config
  labels:
    location: West US 1
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-creds
      key: creds
