apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- target:
    kind: Composition
  patch: |-
    - op: add
      path: /spec/compositeTypeRef
      value:
          apiVersion: ERROR!
          kind: ERROR!

replacements:
- source:
    kind: CompositeResourceDefinition
    fieldPath: spec.names.kind
  targets:
  - select:
      kind: Composition
    fieldPaths:
    - spec.compositeTypeRef.kind

- source:
    kind: CompositeResourceDefinition
    fieldPath: spec.group
  targets:
  - select:
      kind: Composition
    fieldPaths:
    - spec.compositeTypeRef.apiVersion
- source:
    kind: CompositeResourceDefinition
    fieldPath: spec.versions.0.name
  targets:
  - select:
      kind: Composition
    fieldPaths:
    - spec.compositeTypeRef.apiVersion
    options:
      delimiter: '/'
      index: 1

- source:
    kind: CompositeResourceDefinition
    fieldPath: spec.group
  targets:
  - select:
      kind: Composition
    fieldPaths:
    - metadata.name
    options:
      delimiter: '.'
      index: 10 # dirty hack
